version: '3'

services:
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ayushi
      POSTGRES_DB: inventorypostgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
 
  mongodb_data:

  postgres_data:
